// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: vanguard.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Vanguard_ExecuteCommand_FullMethodName = "/vanguard.Vanguard/ExecuteCommand"
)

// VanguardClient is the client API for Vanguard service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VanguardClient interface {
	ExecuteCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error)
}

type vanguardClient struct {
	cc grpc.ClientConnInterface
}

func NewVanguardClient(cc grpc.ClientConnInterface) VanguardClient {
	return &vanguardClient{cc}
}

func (c *vanguardClient) ExecuteCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Vanguard_ExecuteCommand_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VanguardServer is the server API for Vanguard service.
// All implementations must embed UnimplementedVanguardServer
// for forward compatibility
type VanguardServer interface {
	ExecuteCommand(context.Context, *Command) (*Response, error)
	mustEmbedUnimplementedVanguardServer()
}

// UnimplementedVanguardServer must be embedded to have forward compatible implementations.
type UnimplementedVanguardServer struct {
}

func (UnimplementedVanguardServer) ExecuteCommand(context.Context, *Command) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedVanguardServer) mustEmbedUnimplementedVanguardServer() {}

// UnsafeVanguardServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VanguardServer will
// result in compilation errors.
type UnsafeVanguardServer interface {
	mustEmbedUnimplementedVanguardServer()
}

func RegisterVanguardServer(s grpc.ServiceRegistrar, srv VanguardServer) {
	s.RegisterService(&Vanguard_ServiceDesc, srv)
}

func _Vanguard_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VanguardServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vanguard_ExecuteCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VanguardServer).ExecuteCommand(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

// Vanguard_ServiceDesc is the grpc.ServiceDesc for Vanguard service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Vanguard_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vanguard.Vanguard",
	HandlerType: (*VanguardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteCommand",
			Handler:    _Vanguard_ExecuteCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vanguard.proto",
}
